### PR TITLE
Add docker based setup

### PR DESCRIPTION
**Pull request by R0Wi**
Closing #11 

* Server setup based on PHP 8.2
* Env vars take precedence in env.php

### CODE REVIEW

**Comment by amenk** [comment]
Thanks a lot, can you solve the conflicts?

**Comment by R0Wi** [comment]
> Thanks a lot, can you solve the conflicts?

Done @amenk . I needed to adjust quite a few lines in `Env.template` so I decided to add some tests in a separate commit (9ba7732424874930324ea4327b531f1758e93f27). Please let me know if this is okay for you or if you'd rather like me to create a separate PR for this.

Tested the Docker setup and still seems to work 😄

**Comment by amenk** [comment]
Having so much code in the Env.template does not sound very elegant.

Thanks @R0Wi - now that we have composer in place we might as well use dotenv ... 

But it's fine for now :-)

**Comment by R0Wi** [comment]
Using an external library like `dotenv` sounds definitely cleaner and it will reduce the code quite a bit. If you're interested I could create a PR for this aswell. We should just discuss how to bootstrap composer in that case. Would you like to leave it up to the admin to install the dependencies via `composer install` or would you prefer to commit the `vendor` folder?

**Comment by amenk** [comment]
Would leave that to the admin, vendor/ should not be commited ..

In the end of the day it would be nice to be able to use this also as a dependency in PHP projects but as well as standalone .. not sure how well this is possible :-)

**Comment by R0Wi** [comment]
Sounds good 👍 

Think that should be possible somehow, let's see 😄

**Pull request merged**
